name: aws-sam-cli nix

on:
  push:
    branches:
      - main


jobs:
  image_tag:
    name: Run aws version
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Print aws version
        uses: workflow/nix-shell-action@v3
        with:
          packages: aws-sam-cli
          script: |
            sam --version
