name: awscli nix

on:
  push:
    branches:
      - main


jobs:
  image_tag:
    name: Get image tag
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Login to docker registry
        uses: workflow/nix-shell-action@v3
        with:
          packages: awscli2
          script: |
            aws --version
